package greendao.develop.android.multi.table.bean.two;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import greendao.develop.android.multi.table.bean.one.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHOOL_BEAN".
*/
public class SchoolBeanDao extends AbstractDao<SchoolBean, Long> {

    public static final String TABLENAME = "SCHOOL_BEAN";

    /**
     * Properties of entity SchoolBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property SchoolName = new Property(1, String.class, "schoolName", false, "SCHOOL_NAME");
    }

    private DaoSession daoSession;


    public SchoolBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SchoolBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHOOL_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SCHOOL_NAME\" TEXT NOT NULL );"); // 1: schoolName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHOOL_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SchoolBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSchoolName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SchoolBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSchoolName());
    }

    @Override
    protected final void attachEntity(SchoolBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SchoolBean readEntity(Cursor cursor, int offset) {
        SchoolBean entity = new SchoolBean( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1) // schoolName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SchoolBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSchoolName(cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SchoolBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SchoolBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SchoolBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
