package framework.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import framework.sql.NormalBean;

import framework.sql.NormalBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig normalBeanDaoConfig;

    private final NormalBeanDao normalBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        normalBeanDaoConfig = daoConfigMap.get(NormalBeanDao.class).clone();
        normalBeanDaoConfig.initIdentityScope(type);

        normalBeanDao = new NormalBeanDao(normalBeanDaoConfig, this);

        registerDao(NormalBean.class, normalBeanDao);
    }
    
    public void clear() {
        normalBeanDaoConfig.clearIdentityScope();
    }

    public NormalBeanDao getNormalBeanDao() {
        return normalBeanDao;
    }

}
