package framework.sql;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NormalDb".
*/
public class NormalBeanDao extends AbstractDao<NormalBean, Long> {

    public static final String TABLENAME = "NormalDb";

    /**
     * Properties of entity NormalBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PkgName = new Property(1, String.class, "pkgName", false, "PKG_NAME");
        public final static Property AppLabel = new Property(2, String.class, "appLabel", false, "APP_LABEL");
    }


    public NormalBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NormalBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NormalDb\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PKG_NAME\" TEXT NOT NULL ," + // 1: pkgName
                "\"APP_LABEL\" TEXT NOT NULL );"); // 2: appLabel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NormalDb\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NormalBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPkgName());
        stmt.bindString(3, entity.getAppLabel());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NormalBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPkgName());
        stmt.bindString(3, entity.getAppLabel());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NormalBean readEntity(Cursor cursor, int offset) {
        NormalBean entity = new NormalBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // pkgName
            cursor.getString(offset + 2) // appLabel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NormalBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPkgName(cursor.getString(offset + 1));
        entity.setAppLabel(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NormalBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NormalBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NormalBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
