package greendao.develop.android.two;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.develop.android.two.User2x;

import greendao.develop.android.two.User2xDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig user2xDaoConfig;

    private final User2xDao user2xDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        user2xDaoConfig = daoConfigMap.get(User2xDao.class).clone();
        user2xDaoConfig.initIdentityScope(type);

        user2xDao = new User2xDao(user2xDaoConfig, this);

        registerDao(User2x.class, user2xDao);
    }
    
    public void clear() {
        user2xDaoConfig.getIdentityScope().clear();
    }

    public User2xDao getUser2xDao() {
        return user2xDao;
    }

}
