package greendao.develop.android.two;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER2X".
 */
public class User2x {

    private Long id;
    /** Not-null value. */
    private String userName2x;
    /** Not-null value. */
    private String userSex2x;

    public User2x() {
    }

    public User2x(Long id) {
        this.id = id;
    }

    public User2x(Long id, String userName2x, String userSex2x) {
        this.id = id;
        this.userName2x = userName2x;
        this.userSex2x = userSex2x;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName2x() {
        return userName2x;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName2x(String userName2x) {
        this.userName2x = userName2x;
    }

    /** Not-null value. */
    public String getUserSex2x() {
        return userSex2x;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserSex2x(String userSex2x) {
        this.userSex2x = userSex2x;
    }

}
