package com.greendaoexternal;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendaoexternal.ExternalBean;

import com.greendaoexternal.ExternalBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig externalBeanDaoConfig;

    private final ExternalBeanDao externalBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        externalBeanDaoConfig = daoConfigMap.get(ExternalBeanDao.class).clone();
        externalBeanDaoConfig.initIdentityScope(type);

        externalBeanDao = new ExternalBeanDao(externalBeanDaoConfig, this);

        registerDao(ExternalBean.class, externalBeanDao);
    }
    
    public void clear() {
        externalBeanDaoConfig.clearIdentityScope();
    }

    public ExternalBeanDao getExternalBeanDao() {
        return externalBeanDao;
    }

}
